export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "465e1aeb": [() => import(/* webpackChunkName: "465e1aeb" */ "@site/docs/telegraph.md"), "@site/docs/telegraph.md", require.resolveWeak("@site/docs/telegraph.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "68465a84": [() => import(/* webpackChunkName: "68465a84" */ "@site/src/pages/case-study.md"), "@site/src/pages/case-study.md", require.resolveWeak("@site/src/pages/case-study.md")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "9956e33c": [() => import(/* webpackChunkName: "9956e33c" */ "/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "b5bfc595": [() => import(/* webpackChunkName: "b5bfc595" */ "/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json"), "/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/frances/Capstone_Project/Telegraph-Website/telegraph-notify.github.io/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json")],
  "e0383bde": [() => import(/* webpackChunkName: "e0383bde" */ "@site/src/pages/team.tsx"), "@site/src/pages/team.tsx", require.resolveWeak("@site/src/pages/team.tsx")],};
